### ISSUE TITLE
Display of Pictures #01

### ISSUE THREAD

**Issue by Romina875** [Romina875/Recipe_Project#1]
please anyone can change the display of picture 01 and 02
![Capture](https://github.com/Romina875/Recipe_Project/assets/129262527/c448dd96-eae8-41b7-8089-f00aa7700b80)

![Capture](https://github.com/Romina875/Recipe_Project/assets/129262527/e26c9b98-c7e9-4b91-8416-ecc9e5805ad3)

**Comment by parag477** [comment]
I want to work on this issue. Can you please assign mw this?

**Comment by Romina875** [comment]
yeah i will assign you

**Comment by AliGates915** [comment]
Can you describe about your this project.

**Comment by Romina875** [comment]
It is an simple recipe project which contains two recipes first one is GULAB JAMUN and second is CHIKEN JELLFRAZI 
I want someone who can  issue resolve #01

**Comment by AliGates915** [comment]
Ok I will try to Resolve Your issue

**Comment by AliGates915** [comment]
issue#1 is Solved...

**Comment by Romina875** [comment]
great keep it up boy!
